CREATE TABLE FORNECEDOR(
	IDFORNECEDOR		UNIQUEIDENTIFIER	NOT NULL,
	NOME				NVARCHAR(150)		NOT NULL,
	CNPJ				NVARCHAR(25)		NOT NULL,
	PRIMARY KEY(IDFORNECEDOR))
GO

CREATE TABLE PRODUTO(
	IDPRODUTO			UNIQUEIDENTIFIER	NOT NULL,
	NOME				NVARCHAR(150)		NOT NULL,
	DESCRICAO			NVARCHAR(MAX)		NOT NULL,
	FOTO				NVARCHAR(100)		NOT NULL,
	PRECO				DECIMAL(18,2)		NOT NULL,
	QUANTIDADE			INTEGER				NOT NULL,
	IDFORNECEDOR		UNIQUEIDENTIFIER	NOT NULL,
	PRIMARY KEY(IDPRODUTO),
	FOREIGN KEY(IDFORNECEDOR)
		REFERENCES FORNECEDOR(IDFORNECEDOR))
GO